name: note_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  bloc_concurrency: ^0.2.5
  rxdart: ^0.28.0
  equatable: ^2.0.5
  flutter_quill: ^10.4.1
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  objectbox: ^4.0.2

  # => hive is hard to use with flutter_bloc
  hive: ^2.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading.json
